### ISSUE TITLE
About blur kernel generate for meta learning

### ISSUE THREAD

**Issue by liqilei** [JWSoh/MZSR#18]
Hi, thanks for your work.

I noticed in the paper, you mentioned you used both isotropic and anisotropic Gaussian kernels for the blur kernels, while in the code at [here](https://github.com/JWSoh/MZSR/blob/3a1aff3ea1d72b26f91c9c4ba18695108ae697d3/gkernel.py#L55), I found that only random anisotropic Gaussian kernel would be generated. 

Maybe this is my misunderstanding, can you give me some guides on this?

Thanks.

**Comment by JWSoh** [comment]
Actually, you are right. Since, a set of isotropic Gaussian kernels is a subset of anisotropic Gaussian kernels, so we mentioned in that manner.

Precisely, we used anisotropic Gaussian kernels for the blur kernels.

**Comment by liqilei** [comment]
Thanks for your comment. Indeed, isotropic Gaussian kernels is a subset of anisotropic Gaussian kernels.

May I ask more about the N (number of kernels used for meta training)? If my understanding is right, it's a pretty big number, as for every loop, some kernels will be generated. Is this true?

**Comment by JWSoh** [comment]
Yes, you are correct. The number of kernels is theoretically infinite. The kernels are generated based on randomly sampled Gaussian parameters in every loop.

**Comment by liqilei** [comment]
Thank a lot for your comment.
