### ISSUE TITLE
The outputs for arbitary images look bad. What datasets can be used to train the network for new images?

### ISSUE THREAD

**Issue by akhil451** [JWSoh/MZSR#3]
My question was would training the model on a dataset more specific to the use case be a better choice compared to datasets such as Div2k.

**Comment by akhil451** [comment]
If anyone would like to run inference you can run the function below.
`def inference(self, img, img_name):
        '''
          # inp: image_name 
          # op : upscaled image 

        '''
        self.img=img
        print("input image shape:",self.img.shape)
        # self.gt = modcrop(gt, self.scale)

        self.img_name=img_name


        self.sf = np.array(self.scale_factors)
        self.output_shape = np.uint(np.ceil(np.array(self.img.shape[0:2]) * self.scale))

        # Train the network
        # self.quick_test()/
        self.initialize()

        # print('[*] Baseline ')
        self.train()

        # post_processed_output = self.final_test()
        output = self.forward_pass(self.img, (self.img.shape[0]*self.scale,self.img.shape[0]*self.scale,3))

        processed_output=np.round(np.clip(output*255, 0., 255.)).astype(np.uint8)

        if self.save_results:
            if not os.path.exists(self.save_path):
              os.makedirs(self.save_path)
            if not os.path.exists('%s/%02d' % (self.save_path, self.max_iters)):
                os.makedirs('%s/%02d' % (self.save_path, self.max_iters))

            imageio.imsave('%s/%02d/%s.png' % (self.save_path, self.max_iters, os.path.basename(self.img_name)[:-4]),
                                  processed_output)
            # imageio.imsave("test.png",processed_output)`

Add this function test.py and add the same in main.py accordingly.

**Comment by akhil451** [comment]
If anyone would like to run inference you can run the function below.
`
def inference(self, img, img_name):
'''
# inp: image_name
# op : upscaled image

    '''
    self.img=img
    print("input image shape:",self.img.shape)
    # self.gt = modcrop(gt, self.scale)

    self.img_name=img_name


    self.sf = np.array(self.scale_factors)
    self.output_shape = np.uint(np.ceil(np.array(self.img.shape[0:2]) * self.scale))

    # Train the network
    # self.quick_test()/
    self.initialize()

    # print('[*] Baseline ')
    self.train()

    # post_processed_output = self.final_test()
    output = self.forward_pass(self.img, (self.img.shape[0]*self.scale,self.img.shape[0]*self.scale,3))

    processed_output=np.round(np.clip(output*255, 0., 255.)).astype(np.uint8)

    if self.save_results:
        if not os.path.exists(self.save_path):
          os.makedirs(self.save_path)
        if not os.path.exists('%s/%02d' % (self.save_path, self.max_iters)):
            os.makedirs('%s/%02d' % (self.save_path, self.max_iters))

        imageio.imsave('%s/%02d/%s.png' % (self.save_path, self.max_iters, os.path.basename(self.img_name)[:-4]),
                              processed_output)
        # imageio.imsave("test.png",processed_output)`

**Comment by akhil451** [comment]
If anyone would like to run inference you can run the function below.add this to test.py and change the function call in main.py accordingly. 
```
def inference(self, img, img_name):

self.img=img
print("input image shape:",self.img.shape)

self.img_name=img_name


self.sf = np.array(self.scale_factors)
self.output_shape = np.uint(np.ceil(np.array(self.img.shape[0:2]) * self.scale))

# Train the network
# self.quick_test()/
self.initialize()

# print('[*] Baseline ')
self.train()

# post_processed_output = self.final_test()
output = self.forward_pass(self.img, (self.img.shape[0]*self.scale,self.img.shape[0]*self.scale,3))

processed_output=np.round(np.clip(output*255, 0., 255.)).astype(np.uint8)

if self.save_results:
    if not os.path.exists(self.save_path):
      os.makedirs(self.save_path)
    if not os.path.exists('%s/%02d' % (self.save_path, self.max_iters)):
        os.makedirs('%s/%02d' % (self.save_path, self.max_iters))

    imageio.imsave('%s/%02d/%s.png' % (self.save_path, self.max_iters, os.path.basename(self.img_name)[:-4]),
                          processed_output)
    # imageio.imsave("test.png",processed_output)
```

**Comment by JWSoh** [comment]
For an arbitrary image, the kernel information is required to get a plausible output. Without the kernel, the default setting is "bicubic" downsampling method.

I don't think using other dataset instead of DIV2K would give considerable performance gain, because DIV2K is a quite good high-resolution natural image dataset.
Of course, if the case is very specific, using other dataset could be better.
